### ISSUE TITLE
setSettings() bug

### ISSUE THREAD

**Issue by MindLaborDev** [Swifter1243/ReMapper#5]
I get this error when trying to use `.setSetting()` without having "_settings" or "_customData" properties in my Info.dat.
```
if (!(steps[i] in currentObj)) {
                      ^
TypeError: Cannot use 'in' operator to search for '_playerOptions' in undefined
    at jsonSet (ReMapper\src\general.ts:372:23)
    at Difficulty.updateSets (ReMapper\src\beatmap.ts:193:16)
    at Difficulty.setSetting (ReMapper\src\beatmap.ts:157:14)
```

**Comment by Swifter1243** [comment]
thanks, I've fixed this but haven't pushed an update on NPM since there's not enough to do that yet. For now just add the settings param manually and everything should be good on the next update :)
